name: Java CI with Maven 2 Workin

on:
    workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest  
        
    - name: Build with Maven
      run: mvn clean install
  
